-- 
-- Editor SQL for DB table tblService
-- Created by http://editor.datatables.net/generator
-- 

-- IF object_id('tblService', 'U') is null
-- 	CREATE TABLE tblService (
-- 		[ServiceID] int not null identity,
-- 		[servicedate] datetime,
-- 		[orderid] nvarchar(255),
-- 		PRIMARY KEY( [ServiceID] )
-- 	);